### ISSUE TITLE
Issue: Lazy Loading of RunTree client is broken

### ISSUE THREAD

**Issue by ewalker11** [langchain-ai/langsmith-sdk#1004]
### Issue you'd like to raise.

The lazy loading of the client in RunTree introduced in https://github.com/langchain-ai/langsmith-sdk/pull/983 is not working. properly.

```python
from langsmith import RunTree

run_tree = RunTree(name="foo")
run_tree.client.post()
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 5
      1 from langsmith import RunTree
      4 run_tree = RunTree(name=\"foo\")
----> 5 run_tree.client.post()

AttributeError: 'FieldInfo' object has no attribute 'post'
```

### Suggestion:

Use `PrivateAttr` instead: https://docs.pydantic.dev/1.10/usage/models/#private-model-attributes

```python
from pydantic.v1 import BaseModel, Field, PrivateAttr

class Foo(BaseModel):
    _bar: str | None = PrivateAttr(default=None)
    _baz: str | None = Field(default=None)
    
    @property
    def bar(self):
        return self._bar
    
    @property
    def baz(self):
        return self._baz
```
```python
>>> type(Foo().bar).__name__
'NoneType'

>>> type(Foo().baz).__name__
'FieldInfo'
```

**Comment by ewalker11** [comment]
cc @hinthornw
