### ISSUE TITLE
Issue: Problem with traceable decorator and typings (python)

### ISSUE THREAD

**Issue by dfejgelis** [langchain-ai/langsmith-sdk#337]
### Issue you'd like to raise.

hi there! I'm using `traceable` decorator and having some mypy issues. Since the decorator wrapper type hint is `Any` it's messing with the rest of my typings.

Example:
```python
from __future__ import annotations

from langsmith import traceable


@traceable("chain")
def my_chain_2() -> str:
    return "hi there"


@traceable("chain")
def my_chain_1() -> str:
    return my_chain_2()


print(my_chain_1())
```

It's actually not passing mypy: `test-langsmith.py:13:5: error: Returning Any from function declared to return "str"  [no-any-return]`

do you have any feedback for me that it could help?

### Suggestion:

Maybe having generics in the wrapper(s)?

**Comment by hinthornw** [comment]
Thanks for raising! Yeah I can look into this.

**Comment by dfejgelis** [comment]
- Python 3.10.13
- langsmith 0.0.75
- mypy 1.7.1

Thanks in advance for your help, do not hesitate to reach for more details/help on my end

**Comment by dfejgelis** [comment]
@hinthornw it works with 0.0.78! 
Sorry for not creating a PR myself, it was a little out of my comfort zone.

Thanks a ton for fixing this! 🙇 
This issue can be closed to my eyes...

**Comment by hinthornw** [comment]
Great - thanks for raising!
