### ISSUE TITLE
[0.7.9][Regression] type errors with langsmith@0.7.9

### ISSUE THREAD

**Issue by AviVahl** [langchain-ai/langsmith-sdk#3042]
Saw these type errors with the new release.

Steps to reproduce:
```sh
mkdir langsmith-broken-types
cd langsmith-broken-types
npm init -y
npm pkg set type=module
npm i typescript langsmith
npx tsc --init --skipLibCheck false --exactOptionalPropertyTypes false
echo "import * as langsmith from 'langsmith'; console.log(langsmith);" > main.ts
npx tsc --noEmit
```

Results in:
```
Error: node_modules/langsmith/dist/_openapi_client/client.d.ts(27,23): error TS2305: Module '"./internal/headers.js"' has no exported member 'NullableHeaders'.
Error: node_modules/langsmith/dist/_openapi_client/internal/headers.d.ts(2,138): error TS2304: Cannot find name 'NullableHeaders'.
Error: node_modules/langsmith/dist/_openapi_client/internal/headers.d.ts(3,67): error TS2304: Cannot find name 'NullableHeaders'.
Error: node_modules/langsmith/dist/_openapi_client/internal/request-options.d.ts(1,10): error TS2305: Module '"./headers.js"' has no exported member 'NullableHeaders'.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,91): error TS2307: Cannot find module '../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,163): error TS2307: Cannot find module '../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,238): error TS2307: Cannot find module '../../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,316): error TS2307: Cannot find module '../../../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,481): error TS2307: Cannot find module '../../../../../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,568): error TS2307: Cannot find module '../../../../../../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,658): error TS2307: Cannot find module '../../../../../../../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,751): error TS2307: Cannot find module '../../../../../../../../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.
Error: node_modules/langsmith/dist/_openapi_client/internal/types.d.ts(48,847): error TS2307: Cannot find module '../../../../../../../../../../node_modules/undici-types/index.d.ts' or its corresponding type declarations.

```

Same steps work with `langsmith@0.7.8`

**Comment by AviVahl** [comment]
@dqbd @sineha-mani
I'm guessing this one regressed with: https://github.com/langchain-ai/langsmith-sdk/pull/3018

**Comment by yumuzi234** [comment]
looking into it

**Comment by dqbd** [comment]
Hello @AviVahl! The fix has been released in 0.7.10

**Comment by AviVahl** [comment]
Thank you. We've upgraded and everything works as expected. 🙏
